/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BCarousel: typeof import('bootstrap-vue-next')['BCarousel']
    BCarouselSlide: typeof import('bootstrap-vue-next')['BCarouselSlide']
    ExploreCards: typeof import('./src/components/Explore/ExploreCards.vue')['default']
    GeolocationTracker: typeof import('./src/components/GeolocationTracker.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    HomeCards: typeof import('./src/components/Home/HomeCards.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    Login: typeof import('./src/components/Login.vue')['default']
    Modal: typeof import('./src/components/Modal.vue')['default']
    Navbar: typeof import('./src/components/Navbar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Test: typeof import('./src/components/test.vue')['default']
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
  }
}
